[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = [ "full" ] }

thiserror = "1.0.58"

serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"

clap = { version = "4.5.3", features = ["derive"] }

